services:
  database:
    image: postgres:17.0-alpine3.20
    environment:
      POSTGRES_USER: produtoApiUser
      POSTGRES_PASSWORD: P4a55w0rd
      POSTGRES_DB: dotlanche-produto
    ports:
      - "5432:5432"
    volumes:
      - dotLanchesDb:/var/lib/postgresql@17/data

  api:
    build: 
      context: .
      dockerfile: ./src/Drivers/Dotlanche.Produto.WebApi/Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=dotlanche-produto;Username=produtoApiUser;Password=P4a55w0rd

volumes:
  dotLanchesDb:
    name: "98LanchesDb"