apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dotlanche-produto-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dotlanche-produto-deployment
  minReplicas: 2
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 30